#!/usr/bin/env bash
# Daily backup. Two things are irreplaceable and they need different treatment.
#
# The DATABASE can be rebuilt from a crawl, except for the parts that cannot:
# users, profiles, feedback and contract_awards. Feedback is the table match
# precision is computed from, and awards cannot be backfilled from the future.
#
# The RAW ARCHIVE (§8.4) is append-only and is what makes a parser fix
# replayable without re-crawling. It grows; it is synced, not re-copied.
set -euo pipefail

BACKUP_DIR="${BACKUP_DIR:-/opt/tenderradar/backups}"
KEEP_DAYS="${BACKUP_KEEP_DAYS:-14}"
STAMP="$(date -u +%Y%m%d-%H%M)"

mkdir -p "$BACKUP_DIR"

if [ -z "${DATABASE_URL:-}" ]; then
    echo "DATABASE_URL is not set" >&2
    exit 1
fi

# Full dump, compressed. -Fc allows selective restore of a single table.
pg_dump --dbname="$DATABASE_URL" --format=custom --compress=6 \
        --file="$BACKUP_DIR/tenderradar-$STAMP.dump"

# A plain-text dump of the irreplaceable tables as well. If the custom-format
# dump is ever unreadable by a future pg_restore, these are the rows that
# genuinely cannot be regenerated by crawling again.
pg_dump --dbname="$DATABASE_URL" --format=plain --data-only \
        --table=users --table=user_profiles --table=feedback \
        --table=contract_awards --table=payments \
        | gzip -6 > "$BACKUP_DIR/tenderradar-irreplaceable-$STAMP.sql.gz"

# Prune old dumps but never leave zero backups, even if the clock is wrong.
find "$BACKUP_DIR" -name 'tenderradar-*.dump' -mtime "+$KEEP_DAYS" -delete || true
find "$BACKUP_DIR" -name 'tenderradar-irreplaceable-*.sql.gz' -mtime "+$KEEP_DAYS" -delete || true

echo "backup complete: $BACKUP_DIR/tenderradar-$STAMP.dump"
ls -la "$BACKUP_DIR" | tail -5

# A backup you have never restored is a hope, not a backup. Verify the dump is
# at least readable; a silent truncation would otherwise surface only in a
# disaster.
pg_restore --list "$BACKUP_DIR/tenderradar-$STAMP.dump" > /dev/null
echo "dump verified readable"
